/*
 * DialogoHistograma.java
 *
 * Created on __DATE__, __TIME__
 */

package pacote_12643.visao;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import pacote_12643.util.Descritor;

/**
 * Diálogo que exibe um histograma e ações de binarização.
 * @author Tiago
 */
@SuppressWarnings("serial")
public class DialogoHistograma extends javax.swing.JDialog
{
	/** Creates new form DialogoHistograma */
	public DialogoHistograma(java.awt.Frame parent, Descritor descritor)
	{
		super(parent, true);
		initComponents(descritor);
		setSize(400, 400);
		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 * @param descritor 
	 * @param descritor 
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents(Descritor descritor)
	{
		sliderLimiar = new javax.swing.JSlider();
		panelHistograma = new PanelHistograma(descritor);
		panelConteudo = new javax.swing.JPanel();
		panelBotoes = new javax.swing.JPanel();
		btnOk = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		mediator = new MediatorHistograma(this);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Escolha do limiar");
		
		sliderLimiar.setMaximum(255);
		sliderLimiar.setValue(127);
		
		panelConteudo.setLayout(new GridBagLayout());
		GridBagConstraints c = new GridBagConstraints();
		c.ipady = 260;
		c.ipadx = 285;
		c.insets = new Insets(5, 0, 5, 0);
		panelConteudo.add(panelHistograma, c);
		
		c.gridy = 1;
		c.ipady = 0;
		c.ipadx = 255;
		panelConteudo.add(sliderLimiar, c);
		getContentPane().add(panelConteudo, java.awt.BorderLayout.CENTER);

		btnOk.setText("Ok");
		panelBotoes.add(btnOk);

		btnCancelar.setText("Cancelar");
		panelBotoes.add(btnCancelar);

		getContentPane().add(panelBotoes, java.awt.BorderLayout.SOUTH);

		//pack();
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnOk;
	private javax.swing.JPanel panelConteudo;
	private javax.swing.JPanel panelBotoes;
	private PanelHistograma panelHistograma;
	private javax.swing.JSlider sliderLimiar;
	private MediatorHistograma mediator;
	// End of variables declaration//GEN-END:variables

	// Métodos
	public Short getLimiar()
	{
		return mediator.getLimiar();
	}

	public javax.swing.JButton getBtnCancelar()
	{
		return btnCancelar;
	}

	public javax.swing.JButton getBtnOk()
	{
		return btnOk;
	}

	public PanelHistograma getPanelHistograma()
	{
		return panelHistograma;
	}

	public javax.swing.JSlider getSliderLimiar()
	{
		return sliderLimiar;
	}

}